name: plotpad
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.71.0
  llama_cpp_dart:
    path: ./llama_cpp_dart
  isar: ^4.0.0-dev.3
  isar_flutter_libs: ^4.0.0-dev.3
  flutter_secure_storage: ^4.2.1
  encrypt: ^5.0.3
  csv: ^6.0.0
  flutter_riverpod: ^2.6.1
  path_provider: ^2.1.5
  build_runner: ^2.4.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
